GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJBbGZhcml6aSBIaWRheWFoIiwiZW1haWwiOiJhbGZhcml6aUBnbWFpbC5jb20iLCJpYXQiOjE3MTg3MjkwMTQsImV4cCI6MTcxODcyOTAzNH0.yor2sCZWEzpPdafNI9-_1_CjncyqLMvTYBtkaLGJzEE


###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Alfarizi Hidayah",
    "email": "alfarizi@gmail.com",
    "password": "12345678",
    "confPass": "12345678"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "alfarizi@gmail.com",
    "password": "12345678"
}